import type { GameConfig, GameModeConfig } from './types.ts';

export const CHESS_GOLD_CONFIG: GameConfig = {
  startingGold: 3,
  goldPerTurn: 1,
  promotionCost: 3,

  piecePrices: {
    pawn: 1,
    bishop: 3,
    knight: 3,
    rook: 5,
    queen: 8,
  },

  captureRewards: {
    pawn: 0.5,
    bishop: 1.5,
    knight: 1.5,
    rook: 2.5,
    queen: 4,
  },

  placement: {
    maxRow: 3,
    pawnMinRow: 2,
  },

  lootBox: {
    spawnInterval: 4,
    maxActiveBoxes: 1,
    boxesToWin: 6,
    hitsToOpen: 3,
    queenHitsToOpen: 1,
    pawnHitsWithoutMoving: true,
    equipCosts: {
      crossbow: 2,
      'turtle-shell': 2,
      crown: 3.5,
    },
    dropTable: [
      { contents: { type: 'gold', amount: 3 }, weight: 12.5 },
      { contents: { type: 'gold', amount: 4 }, weight: 6.25 },
      { contents: { type: 'gold', amount: 5 }, weight: 6.25 },
      { contents: { type: 'gold', amount: 6 }, weight: 6.25 },
      { contents: { type: 'piece', piece: 'pawn' }, weight: 18.75 },
      { contents: { type: 'piece', piece: 'bishop' }, weight: 12.5 },
      { contents: { type: 'piece', piece: 'knight' }, weight: 12.5 },
      { contents: { type: 'piece', piece: 'rook' }, weight: 6.25 },
      { contents: { type: 'item', item: 'turtle-shell' }, weight: 6.25 },
      { contents: { type: 'item', item: 'crossbow' }, weight: 6.25 },
      { contents: { type: 'item', item: 'crown' }, weight: 6.24 },
      { contents: { type: 'piece', piece: 'king' }, weight: 0.01 },
    ],
  },
};

export const MODE_PRESETS: Record<string, GameModeConfig> = {
  'chess-gold': {
    name: 'Chess Gold',
    goldEconomy: true,
    lootBoxes: false,
    pieceConversion: false,
    placementThrottle: false,
    fogOfWar: false,
    noCheck: false,
    centerPulse: false,
    standardStart: false,
    unrestrictedPlacement: false,
    winConditions: ['checkmate'],
  },
  'loot-boxes': {
    name: 'Loot Boxes',
    goldEconomy: true,
    lootBoxes: true,
    pieceConversion: false,
    placementThrottle: false,
    fogOfWar: false,
    noCheck: false,
    centerPulse: false,
    standardStart: false,
    unrestrictedPlacement: false,
    winConditions: ['checkmate', 'loot-boxes-collected'],
  },
  'gold-mine': {
    name: 'Gold Mine',
    goldEconomy: true,
    lootBoxes: false,
    pieceConversion: false,
    placementThrottle: false,
    fogOfWar: false,
    noCheck: false,
    centerPulse: false,
    standardStart: false,
    unrestrictedPlacement: true,
    winConditions: ['checkmate', 'all-eliminated'],
  },
  conqueror: {
    name: 'Conqueror Chess',
    goldEconomy: false,
    lootBoxes: false,
    pieceConversion: true,
    placementThrottle: false,
    fogOfWar: false,
    noCheck: false,
    centerPulse: false,
    standardStart: true,
    unrestrictedPlacement: false,
    winConditions: ['all-converted'],
  },
  'kings-chess': {
    name: "King's Chess",
    goldEconomy: true,
    lootBoxes: false,
    pieceConversion: true,
    placementThrottle: true,
    fogOfWar: false,
    noCheck: false,
    centerPulse: false,
    standardStart: false,
    unrestrictedPlacement: false,
    winConditions: ['all-converted'],
  },
  siege: {
    name: 'Siege',
    goldEconomy: false,
    lootBoxes: false,
    pieceConversion: false,
    placementThrottle: false,
    fogOfWar: false,
    noCheck: false,
    centerPulse: true,
    standardStart: true,
    unrestrictedPlacement: false,
    winConditions: ['checkmate', 'center-occupied'],
  },
  flashlight: {
    name: 'Flashlight',
    goldEconomy: false,
    lootBoxes: false,
    pieceConversion: false,
    placementThrottle: false,
    fogOfWar: true,
    noCheck: true,
    centerPulse: false,
    standardStart: true,
    unrestrictedPlacement: false,
    winConditions: ['king-captured'],
  },
  'flashlight-gold': {
    name: 'Flashlight Gold',
    goldEconomy: true,
    lootBoxes: false,
    pieceConversion: false,
    placementThrottle: false,
    fogOfWar: true,
    noCheck: true,
    centerPulse: false,
    standardStart: false,
    unrestrictedPlacement: false,
    winConditions: ['king-captured'],
  },
  standard: {
    name: 'Standard Chess',
    goldEconomy: false,
    lootBoxes: false,
    pieceConversion: false,
    placementThrottle: false,
    fogOfWar: false,
    noCheck: false,
    centerPulse: false,
    standardStart: true,
    unrestrictedPlacement: false,
    winConditions: ['checkmate'],
  },
};
